---
logLevel: "INFO"
logFile: ""

numThreads: 2
toolFolder: ""

## Cellbase client configuration
cellbase:
  hosts:
  - "${OSKAR.CELLBASE.REST.HOST}"
  version: "v3"
  database:
    hosts:
    - "localhost"
    user: "user"
    password: "password"
    options: {}
  preferred: "local"

analysis:
  binaries: {
    "plink": "~/soft/plink-1.9/plink",
    "rvtests": "~/soft/rvtests/executable/rvtest"
  }